version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules:/usr/src/app/node_modules
    command: ['npm', 'run', 'dev']
  backend:
    build:
      context: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/usr/src/app
    command:
      ['uvicorn', 'app.main:app', '--host', '0.0.0.0', '--port', '8000', '--reload']
  database:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_manager
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
